version: '3.8'
services:
  api:
    build: .
    container_name: talentmatch-api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=talentmatch
    volumes:
      - .:/app
  mongo:
    image: mongo:6.0
    container_name: talentmatch-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: